### ISSUE TITLE
'Internal Server Error' After Accept credentials

### ISSUE THREAD

**Issue by mobilengine** [elikohen/EKLocalesGenerator#4]
When accepts access to google drive redirects to http://localhost:9292/?code=4/.......... and 
'Internal Server Error' appear
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
WEBrick/1.3.1 (Ruby/2.2.1/2015-02-26) at localhost:9292

The script can not capture token and say 'invalid_token' or does not respond and need to be closed

Blocking line is 207:  
    client.authorization = authorize(client_json_path)

**Comment by elikohen** [comment]
This is a common issue for rvm installed rubies. Should be fixed by updating your ruby version using the command described in the following commit: https://github.com/elikohen/EKLocalesGenerator/commit/48c54ab03b5447ca55777d41957058166d02a04a

**Comment by elikohen** [comment]
Closing this, please reopen if it doesn't work
